<a href="https://colab.research.google.com/github/slavyolov/SU_masters_degree/blob/master/%D0%9E%D0%98%D0%98_%D0%BB%D0%B5%D0%BA%D1%86%D0%B8%D0%B8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Resources :**

- course (e-learn) : https://elearn.uni-sofia.bg/mod/forum/discuss.php?d=67642#p125922
- presentation : https://docs.google.com/presentation/d/1SS5TGMHVAduCcJK4oUP7yfx-ZLgt6yeS/edit#slide=id.p1 
- видео лекции от курса : https://www.youtube.com/playlist?list=PLX9ryRl9v7BCuW9Vv_oJWChVJtRD9HaBM
- Free reasearch papers : https://sci-hub.se/database 
- Books/Articles : https://z-lib.org/
- Books/Articles #2 : https://www.elsevier.com/connect/11-steps-to-structuring-a-science-paper-editors-will-take-seriously 
- Books/Articles #3 : https://www.researchgate.net/

# **Sources of Wisdom :**
- http://www.youtube.com/user/JAVIERLIVAS     - Javier Livas
- http://www.youtube.com/watch?v=jS0zj_dYeBE  -  Igor Nikolic - Complex adaptive systems
- http://www.youtube.com/watch?v=VSCjWT_nI_Q  - General Systems theory
- http://www.youtube.com/watch?v=JwqArbHinCg – Control system
- http://www.gwu.edu/~asc/asc-cyber.html  - What is Cybernetics 
- http://pespmc1.vub.ac.be/ASC/CYBSYSTH.html  - Cybernetics and Systems Theory 
- http://pespmc1.vub.ac.be/ASC/Default.html  - Principia CyberneticaWeb 
- http://pespmc1.vub.ac.be/books/IntroCyb.pdf  - R. Ashby, Introduction to Cybernetics
http://www.art-sciencefactory.com/complexity-map_feb09_april.html  - Interactive map of complexity sciences
- https://academic.oup.com/mind/article/LIX/236/433/986238?login=false - COMPUTING MACHINERY AND INTELLIGENCE (Alan Turing)
- https://www.datasciencesociety.net/juniors-top-10-talks-from-the-ai-congress-of-wearedevelopers-in-vienna/ - Junior’s Top 10 Talks from the AI Congress of WeAreDevelopers in Vienna

Книги:

- Върнър Виндж - Краят на Дъгата  - https://chitanka.info/book/8184-krajat-na-dygata
- Марвин Мински и Хари Харисън - Опцията на Тюринг (2 части) - https://chitanka.info/person/marvin-minsky
- Чарлз Строз - Accelerando (на английски) - https://www.antipope.org/charlie/blog-static/fiction/accelerando/accelerando-intro.html
- Артър Кларк - Профили на Бъдещето - https://chitanka.info/book/2154-profili-na-bydeshteto
- Мичио Каку - Физика на Невъзможното - https://chitanka.info/book/3434-fizika-na-nevyzmozhnoto
 
**Филми:**

- AI
- Transcendance
- Chappie
- Her
- War games
- 2001 A space Odyssey
- Ex Machina
- Tron
- Interstellar
- Blade Runner 2049
- Ghost in a Shell
 

**Youtube канали:**

- 3Blue1Brown
- AI and Games
- Alan Zucconi
- Ars Technica
- blackpenredpen
- Cabrera Research Lab
- Code Bullet
- Code Monkey
- Complexity Explorer
- Computer Science
- Data Science Courses
- Domain of Science
- Dr Peyam
- Dr. Shahin Rostami
- Emergent Garden
- Finematics
- freeCodeCamp.org
- Futurology — An Optimistic Future
- Jason Silva: Shots of Awe
- Julia Galef
- just calculus
- Kaloyan Haralampiev
- Kurzgesagt – In a Nutshell
- Kyle Hill
- Mathemaniac
- Mathologer
- Matt_Parker_2
- Michael Penn
- minutephysics
- Mirror Neuron
- Missing Semester
- N N Taleb's Probability Moocs
- Nigel John Stanford
- Normalized Nerd
- Numberphile
- Oats Studios
- OpenLearn from The Open University
- Pezzza's Work
- Pierre Neis
- Primer
- PythonBobby
- Robots Without Borders
- Science, Technology & the Future
- Sebastian Lague
- Seeker
- sentdex
- Singularity University Summits
- Sixty Symbols
- SmarterEveryDay
- Stand-up Maths
- StatQuest with Josh Starmer
- Steve Brunton
- Steve Mould
- Systems Innovation
- TED
- TED-Ed
- The Andrew Schulz
- The Art of Improvement
- The Bibites: Digital Life
- The Coding Train
- The Royal Institution
- Thunderf00t
- Tibees
- Two Minute Papers
- Up and Atom
- Veritasium
- Vsauce2


# **To be able to do Data Science you need three main components (knowledges) :**
- Math and statistics
- Computer science
- Domain knowledge

# **2022-10-15**

## **Оценки :**
  - задачи в занятието
  - **есе/научна разработка - тема (има технически изисквания) - краен срок 17.02.2023**

## **White hat (facts) :**
  - https://docs.google.com/document/d/1jQ_KX0pY5TXYFoTya-HCOXGYG7TgB36Bjdm0p7jECsI/edit#


## **Gather.town** 
  - https://www.gather.town/
  - онлайн комуникация, ако сме онлайн
  - събота тук, в неделя там

## **brainstorming, positive ideas, summary (10 rows), what is AI**
- Ani, Agi, Asi

## **Лекция/Презентация**

- Karl Popper
- Induction/deduction
  - Аналитичен модел - винаги е валиден, но никога не може да се приложи практично
  - Симулационен модел - работи в конкретни случай (ок за поточна линия за течен шоколад, но не е ок за поточна линия за паста за зъби)
- Universality/Specialization
- Ветрило на възможните **реализации**

## **фундамент при системите за AI**
- Теория на системите
- Кибернетика

## **Imitation/Deus Ex Machina**

- ⏰ minimize entropy - минимизиране на неопределеността
- Charles Babbage (Чарлз Бабидж) - първата сметачна машина
- Ada Lovelace (Ада Лъвлейс) - първия програмист

## **General Systems Theory**
- cybernetics (Robert Wiener) - наука за управление (системи с обратна връзка)

- https://ncase.me/loopy/
- https://app.gather.town/invite?token=tREHcFUITW6_3A-KMBh3
- bit.ly/gather_town1

# **2022-10-16**

- видео записите от лекциите по дисциплината: https://www.youtube.com/playlist?list=PLX9ryRl9v7BCuW9Vv_oJWChVJtRD9HaBM 
- Igor Nikolic - Complex adaptive systems https://www.youtube.com/watch?v=jS0zj_dYeBE

- решение в по-малко от един цикъл на изпълнение (управление в реално време). Например тримесечие (счетоводство), ако системата изработва решение за по-малко време от тримесечие и може да бъде въведено, тогава системата/управлението работи в реално време

- redundency of information
- Clod Shanon - logarithm equal 2 

## **Entropy (information systems)**

In [ ]:
# Calculate the entropy of a distribution for given probability values.
from scipy.stats import entropy

'''
    If only probabilities `pk` are given, the entropy is calculated as
    ``S = -sum(pk * log(pk), axis=axis)``.
'''

entropy(pk=[0.25, 0.125, 0.125, 0, 0.5], base=2)

1.75

- novelty ( 2 events before and after event ). Ще се получи разлика от 2те различни нива на етропията


### **Задачи за оценка на наученото**

In [ ]:
# задача1
h0 = entropy(pk=[0.25, 0.125, 0.125, 0, 0.5], base=2)
h1 = entropy(pk=[0, 0.25, 0.5, 0, 0.25], base=2)

print("h0 ==", h0)
print("h1 ==", h1)

I = h0 - h1
print("задача 1 отг : ", I) # неопределеноста е намалена с 0.25 бита
print(100 * "=")
# задача 2
h0 = entropy(pk=[0.5, 0.5], base=2) # it will be either boy or girl
h1 = entropy(pk=[1, 0], base=2)     # msg_1 = "My wife gave birth to a girl"

print("h0 ==", h0)
print("h1 ==", h1)

I = h0 - h1
print("задача 2 отг : ", I) # неопределеноста е намалена с 1 бит след получаване на новото съобщение
print(100 * "=")

# задача 3
h0 = entropy(pk=[0.2, 0.2, 0.2, 0.2, 0.2], base=2)  # the chance giving right answer without any knowledge is 20%
h1 = entropy(pk=[0.5, 0.5, 0, 0, 0], base=2)        # msg_2 = "Of the 5 possible answers to question 20 of the test, I know for sure that the answer is either A or B"
print("h0 ==", h0)
print("h1 ==", h1)

I = h0 - h1
print("задача 3 отг : ", I) # неопределеноста е намалена с 1.32 бита след получаване на новото съобщение
print(100 * "=")

h0 == 1.75
h1 == 1.5
задача 1 отг :  0.25
h0 == 1.0
h1 == 0.0
задача 2 отг :  1.0
h0 == 2.3219280948873626
h1 == 1.0
задача 3 отг :  1.3219280948873626


- linear vs non linear functions when to use 

Ban Nikola Kasabov - 2tornik seminar

hardware and software neural networks
- Neural Networks meme (multiplication of matrices) . The GPU/TPU is good at it
- Andrew NG - data driven development (machine learning and earning)
- NRDS / statistical decision theory
- is better good or not (if yes -> normal matrix ELSE inverse matrix)


**ЗАДАЧИ ЗА ДРУГИЯ ПЪТ - Петък**

- Loopy : https://basaga.org/basaga_files/loopy.htm
- https://docs.google.com/forms/d/e/1FAIpQLSfYu27IMSsLbHwQD8cBKwbzWTjBq8fy74JWA3gzktvGDUibNA/viewform

In [ ]:
# https://www.intel.com/content/dam/www/program/education/us/en/documents/the-journery-inside/digital/tji-digital-info-handout4.pdf
# https://towardsdatascience.com/the-intuition-behind-shannons-entropy-e74820fe9800
# http://bearcave.com/misl/misl_tech/wavelets/compression/shannon.html

224

# **2022-10-22**

- https://ncase.me/trust-bg/
- Копиращия - „Постъпвай с другите както искаш те да постъпват с теб“
- Игра с нулев резултат. Това е най-честата, за съжаление, представа - че за да спечелим ние, другият трябва да загуби, и обратно.

- Игра с ненулев резултат. Когато полагаме усилието да намерим начин всички да печелят! (Или поне да не губят.) Без възможност да печелят всички доверието не може да еволюира.


**Теория на игрите**

https://towardsdatascience.com/game-theory-in-python-with-nashpy-cb5dceab262c

**Bayes' theorem** 
- https://www.youtube.com/watch?v=pPTLK5hFGnQ
- https://www.youtube.com/watch?v=yBn-eGrRHJU - calculate bayes' probability using decision trees
- https://learning.eupati.eu/mod/book/view.php?id=362&chapterid=388
- условна вероятност == conditional probability (event A under condition B) -> Ral Madrid to win when C.Ronaldo scores
- вектор - поредица от чицла (колоната е вектор, редът също)

**Оптимум на Парето**
- нас ни интересува само границата на Парето. Там е оптимумът
- https://www.sciencedirect.com/topics/engineering/pareto-optimality

# **2022-10-23**

**Fuzzy logic (Размит подход)**

- триъгълно число. Прогноза с доверителни интервали. Примерно прогноза за икономиката с 95% вероятност да има отклонение от 2 стандартни девиации
- при fuzzy logics границите се застъпват (например age variable)
- може да се ползва при credit scoring
- бисектриса (angle bisector (Ъглополовяща))
- fuzzy matching може да се ползва при оправяне на дейтасетове (да речем едно име - Иван Иванов и Иван И. Иванов)

**Algorithms**
- https://stats.stackexchange.com/questions/363669/k-nearest-neighbor-supervised-or-unsupervised-machine-learning
- https://towardsdatascience.com/arimax-with-fourier-series-1d92a976f45f
- Harmonic decompositions (времеви редове) - FFT, HD
  - fourier (синосуиди с различно отместване и дължина на вълната)
- anti clusters (elements to be different but from the same group. Студенти в една група, но с различни умения (по-добър, добър, среден)
- mean_shift https://en.wikipedia.org/wiki/Mean_shift

# Game theory task #1
- http://www.gambit-project.org/ 

In [1]:
!pip install nashpy

import numpy as np
import nashpy as nash

'''
Matrix
  0     | 2    | 4     |6
--------|------|-------|-----
1|  7/0 | 5/10 | 3/12  | 1/6
2| 12/0 | 8/8  | 4/8   | 0/0
3| 15/0 | 9/6  | 3/4   | -3/-6
4| 16/0 | 8/4  | 0/0   | -8/-12
5| 15/0 | 5/2  | -5/-4 | -15/-18
-----------------------------

'''
print("ok")


# Create the game with the payoff matrix
A = np.array([[7, 5, 3, 1],
              [12, 8, 4, 0],
              [15, 9, 3, -3],
              [16, 8, 0, -8],
              [15, 5, -5, -15]
              ]) # A is the row player (the values is each sub array represent the row values)
B = np.array([[0,0,0,0,0],
              [10,8,6,4,2],
              [12,8,4,0,-4],
              [6,0,-6,-12,-18],
              ]
             ) # B is the column player
game1 = nash.Game(A,B)
game1

# Dominance method solution : 1/6 (стратегия 1 по редове и стратегия 6 по колони)

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
  Created wheel for nashpy: filename=nashpy-0.0.21-py3-none-any.whl size=15280 sha256=edc8578833ad8fbfc987dcb33cdcd28120db8bd607696a19f75cbf57498bfff9
  Stored in directory: /root/.cache/pip/wheels/02/08/62/cf4fa931e0a317d180936b266169a57f4bb4eb801465bbe8a1
Successfully built nashpy
ok


Bi matrix game with payoff matrices:

Row player:
[[  7   5   3   1]
 [ 12   8   4   0]
 [ 15   9   3  -3]
 [ 16   8   0  -8]
 [ 15   5  -5 -15]]

Column player:
[[  0   0   0   0   0]
 [ 10   8   6   4   2]
 [ 12   8   4   0  -4]
 [  6   0  -6 -12 -18]]

### Reduction by domiantion (редукция по доминация)
- https://math.libretexts.org/Bookshelves/Applied_Mathematics/Applied_Finite_Mathematics_(Sekhon_and_Bloom)/11%3A_Game_Theory/11.03%3A_Reduction_by_Dominance
- https://www.youtube.com/watch?v=s7rvfZ5l0cY